# Generated by Django 5.1.15 on 2026-09-24 22:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Panel yetkisi',
                'verbose_name_plural': 'Panel yetkileri',
                'permissions': [('access_expenses', 'Giderler'), ('access_reports', 'Raporlar'), ('manage_content', 'İçerik ve Site Ayarları'), ('access_leads', 'Talepler'), ('access_contacts', 'Cariler'), ('view_revenue_today', 'Bugünkü Ciro'), ('view_receivables', 'Tahsil Edilmemiş'), ('change_prices', 'Kasada fiyat, indirim ve takas'), ('delete_records', 'Silme, iptal, iade ve fire')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Kullanıcı adı')),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Zaman')),
                ('kind', models.CharField(choices=[('giris', 'Giriş'), ('cikis', 'Çıkış'), ('hatali_giris', 'Hatalı giriş'), ('islem', 'İşlem'), ('yetkisiz', 'Yetkisiz deneme')], default='islem', max_length=16, verbose_name='Tür')),
                ('action', models.CharField(max_length=160, verbose_name='İşlem')),
                ('target', models.CharField(blank=True, max_length=200, verbose_name='Kayıt')),
                ('target_url', models.CharField(blank=True, max_length=300)),
                ('view_name', models.CharField(blank=True, max_length=100)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='Girilen değerler')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=200, verbose_name='Cihaz')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Hareket kaydı',
                'verbose_name_plural': 'Hareket kayıtları',
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['user', 'at'], name='staff_activ_user_id_5ea3e3_idx'), models.Index(fields=['kind', 'at'], name='staff_activ_kind_5ad4cc_idx')],
            },
        ),
    ]
