# Generated by Django 5.1.15 on 2026-10-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panelaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_expenses', 'Giderler'), ('access_reports', 'Raporlar'), ('manage_content', 'İçerik ve Site Ayarları'), ('access_leads', 'Talepler'), ('access_service', 'Teknik Servis'), ('access_contacts', 'Cariler'), ('view_revenue_today', 'Bugünkü Ciro'), ('view_receivables', 'Tahsil Edilmemiş'), ('change_prices', 'Kasada fiyat, indirim ve takas'), ('delete_records', 'Silme, iptal, iade ve fire')], 'verbose_name': 'Panel yetkisi', 'verbose_name_plural': 'Panel yetkileri'},
        ),
    ]
