# Generated by Django 5.1.15 on 2026-07-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Soru')),
                ('answer', models.TextField(verbose_name='Cevap')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Sık Sorulan Soru',
                'verbose_name_plural': 'Sık Sorulan Sorular',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Bayço Teknoloji', max_length=120, verbose_name='İşletme Adı')),
                ('tagline', models.CharField(blank=True, default='Telefon ve teknolojide güvenin adresi', max_length=200, verbose_name='Slogan')),
                ('phone', models.CharField(default='0850 000 00 00', max_length=40, verbose_name='Telefon')),
                ('whatsapp_number', models.CharField(default='905000000000', help_text='Ülke koduyla, sadece rakam. Örn: 905321234567', max_length=20, verbose_name='WhatsApp Numarası')),
                ('email', models.EmailField(blank=True, default='info@baycoteknoloji.com', max_length=254, verbose_name='E-posta')),
                ('address', models.CharField(blank=True, default='Merkez Mah. Teknoloji Cad. No:1, İstanbul', max_length=255, verbose_name='Adres')),
                ('maps_embed', models.TextField(blank=True, help_text='Google Maps > Paylaş > Harita yerleştir > src bağlantısı', verbose_name='Google Harita Embed URL')),
                ('working_hours', models.CharField(blank=True, default='Hafta içi 09:00 - 20:00 · Cumartesi 10:00 - 18:00', max_length=120, verbose_name='Çalışma Saatleri')),
                ('hero_title', models.CharField(default='Yeni ve İkinci El Telefonda Doğru Adres', max_length=160, verbose_name='Hero Başlık')),
                ('hero_subtitle', models.CharField(blank=True, default='Sıfır ve garantili ikinci el telefonlar, aksesuarlar ve profesyonel teknik servis. Telefonunu sat, takas et veya hemen fiyat teklifi al.', max_length=300, verbose_name='Hero Alt Metin')),
                ('hero_bg', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Hero Arka Plan (mağaza fotoğrafı)')),
                ('hero_cta_text', models.CharField(default='Teklif Al', max_length=40, verbose_name='Hero Buton Metni')),
                ('campaign_active', models.BooleanField(default=True, verbose_name='Kampanya şeridi aktif')),
                ('campaign_text', models.CharField(blank=True, default='🎉 Tüm ikinci el telefonlarda 12 aya varan garanti · Ücretsiz kargo · Kapıda ödeme', max_length=200, verbose_name='Kampanya Metni')),
                ('google_rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=2, verbose_name='Google Puanı')),
                ('google_review_count', models.PositiveIntegerField(default=128, verbose_name='Yorum Sayısı')),
                ('google_review_url', models.URLField(blank=True, verbose_name='Google Yorum Linki')),
                ('footer_about', models.TextField(blank=True, default='Bayço Teknoloji; sıfır ve ikinci el telefon satışı, takas, aksesuar ve teknik servis alanında güvenilir çözüm ortağınız.', verbose_name='Footer Açıklama')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('tiktok', models.URLField(blank=True, verbose_name='TikTok')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Alt Başlık')),
                ('badge', models.CharField(blank=True, help_text='Örn: YENİ, KAMPANYA', max_length=40, verbose_name='Rozet')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='Görsel')),
                ('link_url', models.CharField(blank=True, max_length=255, verbose_name='Bağlantı (opsiyonel)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Duyuru / Slayt',
                'verbose_name_plural': 'Duyurular / Slaytlar',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='Ünvan / Şehir')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Puan (1-5)')),
                ('comment', models.TextField(verbose_name='Yorum')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Fotoğraf')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Müşteri Yorumu',
                'verbose_name_plural': 'Müşteri Yorumları',
                'ordering': ['order', '-id'],
            },
        ),
    ]
