# Generated by Django 5.1.15 on 2026-07-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, default='Hoşnudiye Mah. Kızılcıklı Mahmut Pehlivan Cad. No:12, Tepebaşı / Eskişehir', max_length=255, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_about',
            field=models.TextField(blank=True, default="Eskişehir Bayço Teknoloji; sıfır ve ikinci el telefon satışı, takas, aksesuar ve teknik servis alanında Eskişehir'in güvenilir adresi.", verbose_name='Footer Açıklama'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(blank=True, default='Eskişehir Bayço Teknoloji; sıfır ve garantili ikinci el telefonlar, aksesuar ve profesyonel teknik servis. Telefonunu sat, takas et veya hemen fiyat teklifi al.', max_length=300, verbose_name='Hero Alt Metin'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default="Eskişehir'de Yeni ve İkinci El Telefonun Adresi", max_length=160, verbose_name='Hero Başlık'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, default="Eskişehir'in telefon ve teknoloji adresi", max_length=200, verbose_name='Slogan'),
        ),
    ]
