# Generated by Django 5.1.15 on 2026-08-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0002_alter_sitesettings_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='G- ile başlar. Örn: G-XXXXXXXXXX. Boş bırakılırsa izleme kodu eklenmez.', max_length=40, verbose_name='Google Analytics 4 Ölçüm Kimliği'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text='Search Console > HTML etiketi yönteminde verilen content="..." değeri. Sadece kodu yapıştırın, etiketin tamamını değil.', max_length=120, verbose_name='Google Search Console Doğrulama Kodu'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_saturday',
            field=models.CharField(blank=True, default='10:00-18:00', help_text='Kapalıysa boş bırakın.', max_length=20, verbose_name='Cumartesi saatleri'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_sunday',
            field=models.CharField(blank=True, default='', help_text='Kapalıysa boş bırakın.', max_length=20, verbose_name='Pazar saatleri'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hours_weekday',
            field=models.CharField(blank=True, default='09:00-20:00', help_text='AÇILIŞ-KAPANIŞ biçiminde. Kapalıysa boş bırakın. Örn: 09:00-20:00', max_length=20, verbose_name='Hafta içi saatleri'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Google Haritalar'da mağazaya sağ tıklayınca çıkan ilk sayı. Örn: 39.776667", max_digits=9, null=True, verbose_name='Enlem (latitude)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Google Haritalar'daki ikinci sayı. Örn: 30.520556", max_digits=9, null=True, verbose_name='Boylam (longitude)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='postal_code',
            field=models.CharField(blank=True, default='26130', help_text='Google işletme verisi için. Örn: 26130', max_length=10, verbose_name='Posta Kodu'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_range',
            field=models.CharField(blank=True, default='₺₺', help_text='Google işletme kartı için. ₺ ile ₺₺₺₺ arası.', max_length=10, verbose_name='Fiyat Aralığı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_description',
            field=models.CharField(blank=True, default="Eskişehir Bayço Teknoloji: sıfır ve ikinci el telefon satışı, telefon takas, aksesuar ve teknik servis. Eskişehir'de güvenilir, garantili telefon mağazası.", help_text='Arama sonuçlarındaki açıklama. 150-160 karakter ideal.', max_length=180, verbose_name='SEO Açıklama (ana sayfa)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_keywords',
            field=models.CharField(blank=True, default='Eskişehir telefon, Eskişehir ikinci el telefon, Eskişehir sıfır telefon, telefon takas Eskişehir, telefon tamiri Eskişehir, teknik servis Eskişehir', help_text='Virgülle ayırın. Google sıralamada kullanmaz; diğer motorlar için tutulur.', max_length=300, verbose_name='Anahtar Kelimeler'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(blank=True, default='Eskişehir Sıfır & İkinci El Telefon, Takas | Bayço Teknoloji', help_text="Google'da görünen başlık. 60 karakteri geçmeyin — fazlası kırpılır.", max_length=70, verbose_name='SEO Başlık (ana sayfa)'),
        ),
    ]
