# Generated by Django 5.1.15 on 2026-08-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0003_sitesettings_google_analytics_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='google_review_url',
            field=models.URLField(blank=True, help_text="Google işletme kaydınızın yorum bağlantısı. GİRİLMEZSE yukarıdaki puan Google'a yapısal veri olarak bildirilmez — doğrulanamayan puan bildirmek politika ihlalidir ve sitenin tüm zengin sonuçlarını kaybettirebilir.", verbose_name='Google Yorum Linki'),
        ),
    ]
