# Generated by Django 5.1.15 on 2026-09-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0004_alter_sitesettings_google_review_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='receipt_logo',
            field=models.ImageField(blank=True, help_text='Satış fişinin üstüne basılır. Boş bırakılırsa site logosu kullanılır. Termal yazıcı için otomatik siyah-beyaza çevrilir; düz zeminli bir logo en temiz sonucu verir.', null=True, upload_to='site/', verbose_name='Fiş Logosu'),
        ),
    ]
