# Generated by Django 5.1.15 on 2026-10-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0005_sitesettings_receipt_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='service_terms',
            field=models.TextField(blank=True, default='Cihaz, bu formda yazılı arıza, fiziksel durum ve aksesuarlarla teslim alınmıştır. Formda yazılı olmayan aksesuarlardan servisimiz sorumlu değildir.\nArıza tespitinden sonra kesinleşen ücret müşteriye bildirilir; müşteri onayı alınmadan ücretli işlem yapılmaz.\nTamir sırasında cihazdaki veriler silinebilir. Verilerin yedeklenmesi müşterinin sorumluluğundadır; veri kaybından servisimiz sorumlu tutulamaz.\nSıvı teması, darbe görmüş ya da daha önce başka bir serviste açılmış cihazlarda tamir sırasında veya sonrasında farklı arızalar ortaya çıkabilir.\nEkran kilidi bilgisi yalnızca arıza tespiti ve test için alınır; cihaz teslim edildiğinde kayıtlarımızdan silinir.\nTamiri tamamlanan ya da tamirine onay verilmeyen cihaz, müşteriye haber verildiği tarihten itibaren 30 gün içinde teslim alınmalıdır.\nCihaz, yalnızca bu form veya servis fişi ibraz edilerek teslim edilir.\nKişisel verileriniz 6698 sayılı KVKK kapsamında yalnızca servis işlemi ve sizinle iletişim amacıyla işlenir.', help_text='Cihaz kabul formunun (PDF) altına basılır. Her satır ayrı bir madde olur.', verbose_name='Teknik Servis Şartları'),
        ),
    ]
