# Generated by Django 5.1.15 on 2026-08-09 09:48

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_brand_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Kategori')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Aksesuar Kategorisi',
                'verbose_name_plural': 'Aksesuar Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sayaç',
                'verbose_name_plural': 'Sayaçlar',
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Stok Kodu')),
                ('barcode', models.CharField(blank=True, default='', help_text='Üretici EAN-13 barkodu. Yoksa boş bırakın; stok kodu ile etiket basılabilir.', max_length=64, verbose_name='Barkod')),
                ('name', models.CharField(max_length=160, verbose_name='Ürün Adı')),
                ('variant', models.CharField(blank=True, default='', max_length=120, verbose_name='Model / Varyant')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Alış Fiyatı (₺)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Satış Fiyatı (₺)')),
                ('stock_qty', models.IntegerField(default=0, editable=False, verbose_name='Stok Adedi')),
                ('min_stock_level', models.PositiveIntegerField(default=2, verbose_name='Kritik Stok Seviyesi')),
                ('note', models.TextField(blank=True, default='', verbose_name='Not')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('search_blob', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='catalog.brand', verbose_name='Marka')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='stock.accessorycategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Aksesuar',
                'verbose_name_plural': 'Aksesuarlar',
                'ordering': ['name', 'variant'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='Ad Soyad / Ünvan')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Telefon')),
                ('phone_norm', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-posta')),
                ('tax_no', models.CharField(blank=True, default='', max_length=20, verbose_name='TCKN / VKN')),
                ('company', models.CharField(blank=True, default='', max_length=160, verbose_name='Firma')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Adres')),
                ('is_customer', models.BooleanField(default=True, verbose_name='Müşteri')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Tedarikçi')),
                ('note', models.TextField(blank=True, default='', verbose_name='Not')),
                ('search_blob', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cari',
                'verbose_name_plural': 'Cariler',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='stock_conta_full_na_4037dd_idx'), models.Index(fields=['phone_norm'], name='stock_conta_phone_n_69b5d8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_customer', True), ('is_supplier', True), _connector='OR'), name='contact_has_role')],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: iPhone 13 Pro', max_length=120, verbose_name='Model')),
                ('kind', models.CharField(choices=[('telefon', 'Cep Telefonu'), ('tablet', 'Tablet'), ('saat', 'Akıllı Saat'), ('diger', 'Diğer')], db_index=True, default='telefon', max_length=10, verbose_name='Tür')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_models', to='catalog.brand', verbose_name='Marka')),
            ],
            options={
                'verbose_name': 'Cihaz Modeli',
                'verbose_name_plural': 'Cihaz Modelleri',
                'ordering': ['brand__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Stok Kodu')),
                ('condition', models.CharField(choices=[('sifir', 'Sıfır'), ('ikinci_el', 'İkinci El')], default='ikinci_el', max_length=10, verbose_name='Durum')),
                ('status', models.CharField(choices=[('stokta', 'Stokta'), ('rezerve', 'Rezerve'), ('satildi', 'Satıldı'), ('iade', 'İade'), ('serviste', 'Serviste'), ('kayip', 'Kayıp / Fire')], db_index=True, default='stokta', max_length=10, verbose_name='Stok Durumu')),
                ('imei1', models.CharField(blank=True, default='', max_length=20, verbose_name='IMEI 1')),
                ('imei2', models.CharField(blank=True, default='', max_length=20, verbose_name='IMEI 2')),
                ('serial_no', models.CharField(blank=True, default='', max_length=40, verbose_name='Seri No')),
                ('color', models.CharField(blank=True, default='', max_length=40, verbose_name='Renk')),
                ('storage', models.CharField(blank=True, default='', help_text='Örn: 256GB', max_length=40, verbose_name='Hafıza')),
                ('battery_health', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pil Sağlığı (%)')),
                ('has_box', models.BooleanField(default=False, verbose_name='Kutulu')),
                ('has_invoice', models.BooleanField(default=False, verbose_name='Faturalı')),
                ('defect_note', models.TextField(blank=True, default='', verbose_name='Hasar / Arıza Notu')),
                ('shelf', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Raf / Konum')),
                ('purchase_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Alış Tarihi')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Alış Fiyatı (₺)')),
                ('acquisition', models.CharField(choices=[('alim', 'Satın Alım'), ('takas', 'Takas'), ('iade', 'Müşteri İadesi')], default='alim', max_length=8, verbose_name='Giriş Şekli')),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Etiket Satış Fiyatı (₺)')),
                ('sold_at', models.DateField(blank=True, null=True, verbose_name='Satış Tarihi')),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Satış Bedeli (₺)')),
                ('days_in_stock', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Stokta Kalan Gün')),
                ('warranty_months', models.PositiveSmallIntegerField(choices=[(0, 'Garantisiz'), (1, '1 Ay'), (3, '3 Ay'), (6, '6 Ay'), (12, '12 Ay'), (24, '24 Ay')], default=0, verbose_name='Garanti Süresi')),
                ('warranty_start', models.DateField(blank=True, help_text='İkinci elde üreticinin kalan garantisi devrediliyorsa cihazın ilk satın alma tarihi; boş bırakılırsa satışta bugün atanır.', null=True, verbose_name='Garanti Başlangıcı')),
                ('warranty_end', models.DateField(blank=True, editable=False, null=True, verbose_name='Garanti Bitişi')),
                ('search_blob', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_device', to='catalog.product', verbose_name='Sitedeki İlan')),
                ('sold_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bought_devices', to='stock.contact', verbose_name='Satılan Kişi')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplied_devices', to='stock.contact', verbose_name='Alındığı Kişi / Firma')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='stock.devicemodel', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Cihaz',
                'verbose_name_plural': 'Cihazlar',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('parca', 'Parça'), ('iscilik', 'İşçilik / Servis'), ('nakliye', 'Kargo / Nakliye'), ('kira', 'Kira'), ('fatura', 'Elektrik / Su / İnternet'), ('maas', 'Maaş'), ('vergi', 'Vergi / Resmi'), ('diger', 'Diğer')], max_length=10, verbose_name='Gider Türü')),
                ('title', models.CharField(max_length=160, verbose_name='Açıklama')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (₺)')),
                ('spent_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Tarih')),
                ('note', models.TextField(blank=True, default='', verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='stock.device', verbose_name='İlgili Cihaz')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='stock.contact', verbose_name='Ödenen Yer')),
            ],
            options={
                'verbose_name': 'Gider',
                'verbose_name_plural': 'Giderler',
                'ordering': ['-spent_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(blank=True, default='', editable=False, max_length=20, verbose_name='Fiş No')),
                ('status', models.CharField(choices=[('tamam', 'Tamamlandı'), ('iptal', 'İptal')], db_index=True, default='tamam', max_length=8, verbose_name='Durum')),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Satış Zamanı')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vade Tarihi')),
                ('note', models.TextField(blank=True, default='', verbose_name='Not')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Fiş Tutarı (₺)')),
                ('trade_in_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Takas Tutarı (₺)')),
                ('payable_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Tahsil Edilecek (₺)')),
                ('paid_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Tahsil Edilen (₺)')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Satışı Yapan')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='stock.contact', verbose_name='Müşteri')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Satış',
                'verbose_name_plural': 'Satışlar',
                'ordering': ['-sold_at', '-id'],
                'permissions': [('view_money', 'Maliyet, kâr ve ciro bilgilerini görebilir'), ('manage_stock', 'Stok girişi/düzenlemesi yapabilir')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tahsilat', 'Tahsilat'), ('iade', 'İade / Geri Ödeme')], default='tahsilat', max_length=10, verbose_name='Tür')),
                ('method', models.CharField(choices=[('nakit', 'Nakit'), ('kart', 'Kredi Kartı'), ('havale', 'Havale / EFT'), ('diger', 'Diğer')], default='nakit', max_length=10, verbose_name='Ödeme Şekli')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (₺)')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ödeme Zamanı')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='stock.sale')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=10)),
                ('to_status', models.CharField(max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='stock.device')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stock.sale')),
            ],
            options={
                'verbose_name': 'Cihaz Durum Kaydı',
                'verbose_name_plural': 'Cihaz Durum Kayıtları',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cihaz', 'Cihaz'), ('aksesuar', 'Aksesuar')], max_length=8, verbose_name='Tür')),
                ('item_name', models.CharField(max_length=200, verbose_name='Ürün')),
                ('item_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Kod')),
                ('item_imei', models.CharField(blank=True, default='', max_length=20, verbose_name='IMEI')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Birim Fiyat (₺)')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Birim Maliyet (₺)')),
                ('line_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='İndirim (₺)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='KDV %')),
                ('line_total', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price')), '-', models.F('line_discount')), output_field=models.DecimalField(decimal_places=2, max_digits=14), verbose_name='Satır Tutarı')),
                ('line_cost', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_cost')), output_field=models.DecimalField(decimal_places=2, max_digits=14), verbose_name='Satır Maliyeti')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='İade Zamanı')),
                ('return_reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='stock.accessory')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='stock.device')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.sale')),
            ],
            options={
                'verbose_name': 'Satış Kalemi',
                'verbose_name_plural': 'Satış Kalemleri',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Giriş +, çıkış −', verbose_name='Miktar')),
                ('reason', models.CharField(choices=[('acilis', 'Açılış Stoğu'), ('giris', 'Mal Girişi'), ('satis', 'Satış'), ('iade', 'İade'), ('sayim', 'Sayım Düzeltmesi'), ('fire', 'Fire / Kayıp')], db_index=True, max_length=8, verbose_name='Sebep')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Birim Alış (₺)')),
                ('balance_after', models.IntegerField(editable=False)),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.accessory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='stock.saleitem')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TradeIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Takas Bedeli (₺)')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trade_in', to='stock.device', verbose_name='Alınan Cihaz')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_ins', to='stock.sale')),
            ],
            options={
                'verbose_name': 'Takas',
                'verbose_name_plural': 'Takaslar',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['is_active', 'stock_qty'], name='stock_acces_is_acti_8ad88f_idx'),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['name'], name='stock_acces_name_e23082_idx'),
        ),
        migrations.AddIndex(
            model_name='accessory',
            index=models.Index(fields=['barcode'], name='stock_acces_barcode_752a1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessory',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('barcode',), name='uniq_accessory_barcode'),
        ),
        migrations.AddConstraint(
            model_name='accessory',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0), ('price__gte', 0)), name='accessory_prices_nonneg'),
        ),
        migrations.AddIndex(
            model_name='devicemodel',
            index=models.Index(fields=['name'], name='stock_devic_name_d21cf2_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicemodel',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='uniq_devicemodel_brand_name'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status', 'purchase_date'], name='stock_devic_status_13a423_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status', 'device_model'], name='stock_devic_status_e1e5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['sold_at'], name='stock_devic_sold_at_9a7cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['warranty_end'], name='stock_devic_warrant_d3b928_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['stock_code'], name='stock_devic_stock_c_6d0c94_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['imei1'], name='stock_devic_imei1_7f63cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('imei1', ''), _negated=True), fields=('imei1',), name='uniq_device_imei1'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('imei2', ''), _negated=True), fields=('imei2',), name='uniq_device_imei2'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_no', ''), _negated=True), fields=('serial_no',), name='uniq_device_serial'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='device_cost_nonneg'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['device', 'spent_on'], name='stock_expen_device__d98af1_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['spent_on', 'kind'], name='stock_expen_spent_o_b2a243_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['kind'], name='stock_expen_kind_25f71f_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('device__isnull', True), ('kind__in', ['parca', 'iscilik', 'nakliye', 'diger']), _connector='OR'), name='expense_device_kind_valid'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', 'sold_at'], name='stock_sale_status_834918_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['due_date'], name='stock_sale_due_dat_10fa8f_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer', 'status'], name='stock_sale_custome_58cf0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt_no', ''), _negated=True), fields=('receipt_no',), name='uniq_sale_receipt'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sale', 'paid_at'], name='stock_payme_sale_id_0e6af7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at', 'method'], name='stock_payme_paid_at_effd7f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['kind', 'paid_at'], name='stock_payme_kind_ceb840_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='devicestatuslog',
            index=models.Index(fields=['device', 'created_at'], name='stock_devic_device__9af4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['sale', 'kind'], name='stock_salei_sale_id_04a1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['kind', 'returned_at'], name='stock_salei_kind_7431c8_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['returned_at'], name='stock_salei_returne_52e639_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accessory__isnull', True), ('device__isnull', False), ('kind', 'cihaz')), models.Q(('accessory__isnull', False), ('device__isnull', True), ('kind', 'aksesuar')), _connector='OR'), name='saleitem_target_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'aksesuar'), ('quantity', 1), _connector='OR'), name='saleitem_device_qty_one'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='saleitem_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_discount__gte', 0)), name='saleitem_discount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.UniqueConstraint(condition=models.Q(('device__isnull', False), ('returned_at__isnull', True)), fields=('device',), name='uniq_active_device_line'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['accessory', 'created_at'], name='stock_stock_accesso_d39cde_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='stock_stock_created_69d383_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='movement_qty_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='tradein',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='tradein_amount_nonneg'),
        ),
    ]
