# Generated by Django 5.1.15 on 2026-08-09 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='warranty_months',
            field=models.PositiveSmallIntegerField(default=0, help_text='Kalan garanti ay olarak. Üreticinin devreden garantisi için 17, 22, 23 gibi ara değerler de girilebilir.', validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Garanti Süresi (ay)'),
        ),
    ]
