# Generated by Django 5.1.15 on 2026-08-09 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_brand_is_public'),
        ('stock', '0002_alter_device_warranty_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['-updated_at'], name='stock_devic_updated_36f43d_idx'),
        ),
    ]
