# Generated by Django 5.1.15 on 2026-10-04 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_device_stock_devic_updated_36f43d_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='warranty_months',
            field=models.PositiveSmallIntegerField(default=0, help_text='Garanti başlangıcından itibaren toplam süre. Başlangıç tarihi girilmişse üretici garantisi olarak 24 ay yazılır.', validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Garanti Süresi (ay)'),
        ),
    ]
