# Generated by Django 5.1.15 on 2026-10-05 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_warranty_months_help'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, verbose_name='Gerekçe')),
                ('status', models.CharField(choices=[('bekliyor', 'Onay bekliyor'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi'), ('gecersiz', 'Geçersiz')], default='bekliyor', max_length=10, verbose_name='Durum')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Talep zamanı')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Karar zamanı')),
                ('decision_note', models.CharField(blank=True, default='', max_length=200, verbose_name='Karar notu')),
            ],
            options={
                'verbose_name': 'Satıcı Değişikliği',
                'verbose_name_plural': 'Satıcı Değişiklikleri',
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['cashier', 'sold_at'], name='stock_sale_cashier_fb1dfe_idx'),
        ),
        migrations.AddField(
            model_name='sellerchange',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Karar veren'),
        ),
        migrations.AddField(
            model_name='sellerchange',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Eski satıcı'),
        ),
        migrations.AddField(
            model_name='sellerchange',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Talep eden'),
        ),
        migrations.AddField(
            model_name='sellerchange',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_changes', to='stock.sale', verbose_name='Satış'),
        ),
        migrations.AddField(
            model_name='sellerchange',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yeni satıcı'),
        ),
        migrations.AddIndex(
            model_name='sellerchange',
            index=models.Index(fields=['status', 'requested_at'], name='stock_selle_status_83ac3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellerchange',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'bekliyor')), fields=('sale',), name='uniq_pending_seller_change'),
        ),
    ]
