# Generated by Django 5.1.15 on 2026-10-05 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F, OuterRef, Subquery
from django.db.models.functions import Coalesce


def backfill_updated_by(apps, schema_editor):
    """Mevcut kayıtlara en iyi tahmin: son durum kaydını / stok hareketini
    yazan kişi (cihazda yoksa kaydı açan). Kart düzenlemeleri loglanmadığı için
    birebir doğru olmayabilir; yeni işlemlerden itibaren alan kesindir.

    QuerySet.update() auto_now'ı tetiklemez — updated_at ve dolayısıyla
    "Son İşlem" sıralaması değişmez."""
    Device = apps.get_model("stock", "Device")
    DeviceStatusLog = apps.get_model("stock", "DeviceStatusLog")
    Accessory = apps.get_model("stock", "Accessory")
    StockMovement = apps.get_model("stock", "StockMovement")

    last_log = (DeviceStatusLog.objects
                .filter(device=OuterRef("pk"), created_by__isnull=False)
                .order_by("-created_at", "-id").values("created_by")[:1])
    Device.objects.update(updated_by=Coalesce(Subquery(last_log), F("created_by")))

    last_move = (StockMovement.objects
                 .filter(accessory=OuterRef("pk"), created_by__isnull=False)
                 .order_by("-created_at", "-id").values("created_by")[:1])
    Accessory.objects.update(updated_by=Subquery(last_move))


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_seller_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Son İşlemi Yapan'),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Son İşlemi Yapan'),
        ),
        migrations.RunPython(backfill_updated_by, migrations.RunPython.noop),
    ]
