# Generated by Django 5.1.15 on 2026-10-05 10:31

import apps.service.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0005_seller_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Tamirhane Adı')),
                ('contact_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Yetkili')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Adres')),
                ('iban', models.CharField(blank=True, default='', max_length=40, verbose_name='IBAN')),
                ('note', models.TextField(blank=True, default='', verbose_name='Not')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('search_blob', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tamirhane',
                'verbose_name_plural': 'Tamirhaneler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Servis No')),
                ('imei', models.CharField(blank=True, default='', max_length=20, verbose_name='IMEI')),
                ('serial_no', models.CharField(blank=True, default='', max_length=40, verbose_name='Seri No')),
                ('color', models.CharField(blank=True, default='', max_length=40, verbose_name='Renk')),
                ('lock_pin', models.CharField(blank=True, default='', max_length=40, verbose_name='Ekran Parolası / PIN')),
                ('lock_pattern', models.CharField(blank=True, default='', max_length=17, validators=[apps.service.models.validate_pattern], verbose_name='Ekran Deseni')),
                ('received_items', models.JSONField(blank=True, default=list, verbose_name='Teslim Alınan Aksesuarlar')),
                ('received_note', models.CharField(blank=True, default='', max_length=200, verbose_name='Diğer Aksesuar')),
                ('condition_note', models.TextField(blank=True, default='', help_text='Çizik, kırık, ekran yanığı, sıvı teması…', verbose_name='Fiziksel Durum')),
                ('complaint', models.TextField(verbose_name='Müşteri Şikâyeti / Arıza')),
                ('diagnosis', models.TextField(blank=True, default='', verbose_name='Tespit / Yapılan İşlem')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tahmini Ücret (₺)')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Müşteriden alınacak kesin ücret.', max_digits=12, null=True, verbose_name='Servis Ücreti (₺)')),
                ('estimated_ready', models.DateField(blank=True, null=True, verbose_name='Tahmini Teslim')),
                ('status', models.CharField(choices=[('kabul', 'Teslim Alındı'), ('inceleme', 'Arıza Tespiti'), ('onay', 'Müşteri Onayı Bekleniyor'), ('tamirde', 'Tamirde'), ('tamirhane', 'Tamirhanede'), ('hazir', 'Teslime Hazır'), ('teslim', 'Teslim Edildi'), ('iade', 'Tamirsiz İade')], db_index=True, default='kabul', max_length=10, verbose_name='Durum')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Teslim Alınma')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kapanış')),
                ('paid_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Tahsil Edilen (₺)')),
                ('note', models.TextField(blank=True, default='', help_text='Müşteriye basılan belgelerde görünmez.', verbose_name='İç Not')),
                ('search_blob', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_tickets', to='stock.contact', verbose_name='Müşteri')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_tickets', to='stock.devicemodel', verbose_name='Cihaz (Marka / Model)')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
            ],
            options={
                'verbose_name': 'Servis Kaydı',
                'verbose_name_plural': 'Servis Kayıtları',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=10)),
                ('to_status', models.CharField(max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='service.serviceticket')),
            ],
            options={
                'verbose_name': 'Servis Durum Kaydı',
                'verbose_name_plural': 'Servis Durum Kayıtları',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tahsilat', 'Tahsilat'), ('iade', 'İade / Geri Ödeme')], default='tahsilat', max_length=10, verbose_name='Tür')),
                ('method', models.CharField(choices=[('nakit', 'Nakit'), ('kart', 'Kredi Kartı'), ('havale', 'Havale / EFT'), ('diger', 'Diğer')], default='nakit', max_length=10, verbose_name='Ödeme Şekli')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (₺)')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ödeme Zamanı')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='service.serviceticket')),
            ],
            options={
                'verbose_name': 'Servis Ödemesi',
                'verbose_name_plural': 'Servis Ödemeleri',
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOutsource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=200, verbose_name='Yapılacak İş')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Tamirhaneye ödenecek tutar.', max_digits=12, null=True, verbose_name='Tamirhane Bedeli (₺)')),
                ('sent_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Gönderim Tarihi')),
                ('returned_at', models.DateField(blank=True, null=True, verbose_name='Dönüş Tarihi')),
                ('status', models.CharField(choices=[('gonderildi', 'Tamirhanede'), ('dondu', 'Döndü'), ('iptal', 'İptal')], db_index=True, default='gonderildi', max_length=10, verbose_name='Durum')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='service.repairshop', verbose_name='Tamirhane')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outsources', to='service.serviceticket', verbose_name='Servis Kaydı')),
            ],
            options={
                'verbose_name': 'Tamirhane İşi',
                'verbose_name_plural': 'Tamirhane İşleri',
                'ordering': ['-sent_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('parca', 'Parça'), ('iscilik', 'İşçilik'), ('diger', 'Diğer')], default='parca', max_length=10, verbose_name='Tür')),
                ('title', models.CharField(max_length=160, verbose_name='Açıklama')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (₺)')),
                ('spent_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Tarih')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='service.serviceticket')),
            ],
            options={
                'verbose_name': 'Servis Maliyeti',
                'verbose_name_plural': 'Servis Maliyetleri',
                'ordering': ['spent_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RepairShopPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (₺)')),
                ('method', models.CharField(choices=[('nakit', 'Nakit'), ('kart', 'Kredi Kartı'), ('havale', 'Havale / EFT'), ('diger', 'Diğer')], default='nakit', max_length=10, verbose_name='Ödeme Şekli')),
                ('paid_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ödeme Tarihi')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='service.repairshop', verbose_name='Tamirhane')),
                ('outsource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='service.serviceoutsource', verbose_name='İlgili İş')),
            ],
            options={
                'verbose_name': 'Tamirhane Ödemesi',
                'verbose_name_plural': 'Tamirhane Ödemeleri',
                'ordering': ['-paid_at', '-id'],
                'indexes': [models.Index(fields=['shop', 'paid_at'], name='service_rep_shop_id_12d10c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='repairshoppayment_amount_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['status', 'received_at'], name='service_ser_status_b2ad1d_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['closed_at'], name='service_ser_closed__880976_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['customer', 'received_at'], name='service_ser_custome_e683d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estimated_price__isnull', True), ('estimated_price__gte', 0), _connector='OR'), models.Q(('final_price__isnull', True), ('final_price__gte', 0), _connector='OR')), name='serviceticket_prices_nonneg'),
        ),
        migrations.AddIndex(
            model_name='servicepayment',
            index=models.Index(fields=['paid_at'], name='service_ser_paid_at_0fa015_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='servicepayment_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='serviceoutsource',
            index=models.Index(fields=['shop', 'status'], name='service_ser_shop_id_881206_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceoutsource',
            constraint=models.CheckConstraint(condition=models.Q(('cost__isnull', True), ('cost__gte', 0), _connector='OR'), name='serviceoutsource_cost_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='serviceoutsource',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'gonderildi')), fields=('ticket',), name='uniq_active_outsource'),
        ),
        migrations.AddConstraint(
            model_name='servicecost',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='servicecost_amount_positive'),
        ),
    ]
