# Generated by Django 5.1.15 on 2026-10-05 10:45

import django.db.models.deletion
from django.db import migrations, models


def rename_status(apps, schema_editor, old="tamirhane", new="dis_servis"):
    """Arayüzde "tamirhane" kelimesi kaldırıldı; kayıtlı durum değeri de
    (adres çubuğunda ?durum=… olarak görünür) yeni adına taşınır."""
    Ticket = apps.get_model("service", "ServiceTicket")
    Log = apps.get_model("service", "ServiceStatusLog")
    Ticket.objects.filter(status=old).update(status=new)
    Log.objects.filter(from_status=old).update(from_status=new)
    Log.objects.filter(to_status=old).update(to_status=new)


def restore_status(apps, schema_editor):
    rename_status(apps, schema_editor, old="dis_servis", new="tamirhane")


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repairshop',
            options={'ordering': ['name'], 'verbose_name': 'Teknik Servis', 'verbose_name_plural': 'Teknik Servisler'},
        ),
        migrations.AlterModelOptions(
            name='repairshoppayment',
            options={'ordering': ['-paid_at', '-id'], 'verbose_name': 'Teknik Servis Ödemesi', 'verbose_name_plural': 'Teknik Servis Ödemeleri'},
        ),
        migrations.AlterModelOptions(
            name='serviceoutsource',
            options={'ordering': ['-sent_at', '-id'], 'verbose_name': 'Teknik Servis İşi', 'verbose_name_plural': 'Teknik Servis İşleri'},
        ),
        migrations.AlterField(
            model_name='repairshop',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Teknik Servis Adı'),
        ),
        migrations.AlterField(
            model_name='repairshoppayment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='service.repairshop', verbose_name='Teknik Servis'),
        ),
        migrations.AlterField(
            model_name='serviceoutsource',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Teknik servise ödenecek tutar.', max_digits=12, null=True, verbose_name='Teknik Servis Bedeli (₺)'),
        ),
        migrations.AlterField(
            model_name='serviceoutsource',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='service.repairshop', verbose_name='Teknik Servis'),
        ),
        migrations.AlterField(
            model_name='serviceoutsource',
            name='status',
            field=models.CharField(choices=[('gonderildi', 'Teknik Serviste'), ('dondu', 'Döndü'), ('iptal', 'İptal')], db_index=True, default='gonderildi', max_length=10, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('kabul', 'Teslim Alındı'), ('inceleme', 'Arıza Tespiti'), ('onay', 'Müşteri Onayı Bekleniyor'), ('tamirde', 'Tamirde'), ('dis_servis', 'Teknik Serviste'), ('hazir', 'Teslime Hazır'), ('teslim', 'Teslim Edildi'), ('iade', 'Tamirsiz İade')], db_index=True, default='kabul', max_length=10, verbose_name='Durum'),
        ),
        migrations.RunPython(rename_status, restore_status),
    ]
