# Generated by Django 5.1.15 on 2026-07-15 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_handled', models.BooleanField(default=False, verbose_name='Okundu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('phone', models.CharField(max_length=40, verbose_name='Telefon')),
                ('device', models.CharField(max_length=120, verbose_name='Cihaz')),
                ('issue', models.CharField(max_length=200, verbose_name='Arıza')),
                ('note', models.TextField(blank=True, verbose_name='Ek Bilgi')),
                ('is_handled', models.BooleanField(default=False, verbose_name='İşleme Alındı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Servis Talebi',
                'verbose_name_plural': 'Servis Talepleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sat', 'Telefonunu Sat / Takas'), ('al', 'Fiyat Teklifi Al')], default='sat', max_length=4, verbose_name='Tür')),
                ('name', models.CharField(max_length=120, verbose_name='Ad Soyad')),
                ('phone', models.CharField(max_length=40, verbose_name='Telefon')),
                ('brand', models.CharField(blank=True, max_length=80, verbose_name='Marka')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='Model')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='Yıl')),
                ('storage', models.CharField(blank=True, max_length=40, verbose_name='Hafıza')),
                ('condition', models.CharField(blank=True, max_length=80, verbose_name='Durum')),
                ('note', models.TextField(blank=True, verbose_name='Not / Ek Bilgi')),
                ('is_handled', models.BooleanField(default=False, verbose_name='İşleme Alındı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='catalog.product', verbose_name='İlgili Ürün')),
            ],
            options={
                'verbose_name': 'Teklif Talebi',
                'verbose_name_plural': 'Teklif Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
