# Generated by Django 5.1.15 on 2026-09-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='condition',
            field=models.CharField(blank=True, max_length=255, verbose_name='Durum'),
        ),
    ]
