# Generated by Django 5.1.15 on 2026-07-15 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Marka')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Logo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug')),
                ('condition', models.CharField(choices=[('sifir', 'Sıfır'), ('ikinci_el', 'İkinci El')], default='sifir', max_length=10, verbose_name='Durum')),
                ('price', models.DecimalField(blank=True, decimal_places=0, help_text="Boş bırakılırsa 'Fiyat sorunuz' gösterilir.", max_digits=10, null=True, verbose_name='Fiyat (TL)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, help_text='İndirim göstermek için (opsiyonel).', max_digits=10, null=True, verbose_name='Eski Fiyat (TL)')),
                ('storage', models.CharField(blank=True, help_text='Örn: 128GB', max_length=40, verbose_name='Hafıza')),
                ('color', models.CharField(blank=True, max_length=40, verbose_name='Renk')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Model Yılı')),
                ('condition_grade', models.CharField(blank=True, help_text='İkinci el için: Sıfır ayarında / Çok iyi / İyi vb.', max_length=60, verbose_name='Kozmetik Durum')),
                ('warranty', models.CharField(blank=True, default='', max_length=60, verbose_name='Garanti')),
                ('short_desc', models.CharField(blank=True, max_length=200, verbose_name='Kısa Açıklama')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Kapak Görseli')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif (yayında)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand', verbose_name='Marka')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Görsel')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Ürün Görseli',
                'verbose_name_plural': 'Ürün Görselleri',
                'ordering': ['order', 'id'],
            },
        ),
    ]
