# Generated by Django 5.1.15 on 2026-08-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Kapalıysa marka yalnızca stok/panelde görünür (örn. aksesuar markaları).', verbose_name='Sitede Göster'),
        ),
    ]
